#!/bin/bash

set -e
set -o pipefail
#source config.env



set -e
set -o pipefail

IP_MON_SUBNET="192.168.104"

NAME_SERVER_MONDIST="pmdtip1"
IP_SERVER_MONDIST="${IP_MON_SUBNET}.132"

#수집서버
NAME_SERVER_MONCOLLECT01="pmctip1"
IP_SERVER_MONCOLLECT01="${IP_MON_SUBNET}.4"

NAME_SERVER_MONCOLLECT02="pmctip2"
IP_SERVER_MONCOLLECT02="${IP_MON_SUBNET}.13"

NAME_SERVER_MONCOLLECT03="pmctip3"
IP_SERVER_MONCOLLECT03="${IP_MON_SUBNET}.19"

#처리서버
NAME_SERVER_MONPROC01="pmprip1"
IP_SERVER_MONPROC01="${IP_MON_SUBNET}.17"

NAME_SERVER_MONPROC02="pmprip2"
IP_SERVER_MONPROC02="${IP_MON_SUBNET}.10"

NAME_SERVER_MONPROC03="pmprip3"
IP_SERVER_MONPROC03="${IP_MON_SUBNET}.14"


#웹서버
NAME_SERVER_MONWEB01="pmwbip1"
IP_SERVER_MONWEB01="${IP_MON_SUBNET}.18"

NAME_SERVER_MONWEB02="pmwbip2"
IP_SERVER_MONWEB02="${IP_MON_SUBNET}.9"

#DB서버
NAME_SERVER_MONDB01="pmndip1"
IP_SERVER_MONDB01="${IP_MON_SUBNET}.6"

NAME_SERVER_MONDB02="pmndip2"
IP_SERVER_MONDB02="${IP_MON_SUBNET}.11"

NAME_SERVER_MONDB03="pmndip3"
IP_SERVER_MONDB03="${IP_MON_SUBNET}.15"

#로그DB서버
NAME_SERVER_MONLOGDB01="pmldip1"
IP_SERVER_MONLOGDB01="${IP_MON_SUBNET}.22"

NAME_SERVER_MONLOGDB02="pmldip2"
IP_SERVER_MONLOGDB02="${IP_MON_SUBNET}.27"

NAME_SERVER_MONLOGDB03="pmldip3"
IP_SERVER_MONLOGDB03="${IP_MON_SUBNET}.25"

#메트릭DB서버
NAME_SERVER_MONMETRICDB01="pmmdip1"
IP_SERVER_MONMETRICDB01="${IP_MON_SUBNET}.23"

NAME_SERVER_MONMETRICDB02="pmmdip2"
IP_SERVER_MONMETRICDB02="${IP_MON_SUBNET}.34"

NAME_SERVER_MONMETRICDB03="pmmdip3"
IP_SERVER_MONMETRICDB03="${IP_MON_SUBNET}.21"

#LB 서버
NAME_SERVER_MONLB01="pmlbip1"
IP_SERVER_MONLB01="${IP_MON_SUBNET}.28"

NAME_SERVER_MONLB02="pmlbip2"
IP_SERVER_MONLB02="${IP_MON_SUBNET}.33"

NAME_SERVER_MONLBVIP="monlb"
IP_SERVER_MONLBVIP="${IP_MON_SUBNET}.83"

#배치서버
NAME_SERVER_MONBATCH="pmbtip1"
IP_SERVER_MONBATCH="${IP_MON_SUBNET}.7"

declare -a SERVERS_COLLECT=("${NAME_SERVER_MONCOLLECT01}" "${NAME_SERVER_MONCOLLECT02}" "${NAME_SERVER_MONCOLLECT03}")
declare -a SERVERS_PROC=("${NAME_SERVER_MONPROC01}" "${NAME_SERVER_MONPROC02}" "${NAME_SERVER_MONPROC03}")
declare -a SERVERS_WEB=("${NAME_SERVER_MONWEB01}" "${NAME_SERVER_MONWEB02}")
declare -a SERVERS_DB=("${NAME_SERVER_MONDB01}" "${NAME_SERVER_MONDB02}" "${NAME_SERVER_MONDB03}")
declare -a SERVERS_LOGDB=("${NAME_SERVER_MONLOGDB01}" "${NAME_SERVER_MONLOGDB02}" "${NAME_SERVER_MONLOGDB03}")
declare -a SERVERS_METRICDB=("${NAME_SERVER_MONMETRICDB01}" "${NAME_SERVER_MONMETRICDB02}" "${NAME_SERVER_MONMETRICDB03}")
declare -a SERVERS_LB=("${NAME_SERVER_MONLB01}" "${NAME_SERVER_MONLB02}")
declare -a SERVERS_BATCH=("${NAME_SERVER_MONBATCH}")



function checkPort(){

  nc_result=`nc -z $1 $2; echo $?`

  if [ $nc_result != 0 ];
  then
    message="[ERROR] $1 $3 is not running.Please check process "
  else
    message="[RUNNING] $1 $3 is running."
  fi

  echo "$message"

}


for idx in ${!SERVERS_COLLECT[*]}
do

  TARGET_HOST=${SERVERS_COLLECT[${idx}]}

  checkPort $TARGET_HOST 8094 "telegraf"
  checkPort $TARGET_HOST 5044 "logstash"
  checkPort $TARGET_HOST 9092 "kafka"

done

for idx in ${!SERVERS_PROC[*]}
do

  TARGET_HOST=${SERVERS_PROC[${idx}]}

  checkPort $TARGET_HOST 9991 "msg-proc-daemon"
done

for idx in ${!SERVERS_WEB[*]}
do

  TARGET_HOST=${SERVERS_WEB[${idx}]}

  checkPort $TARGET_HOST 9000 "monitoring-api"
done

for idx in ${!SERVERS_DB[*]}
do

  TARGET_HOST=${SERVERS_DB[${idx}]}

  checkPort $TARGET_HOST 3306 "mysql"
done

for idx in ${!SERVERS_LOGDB[*]}
do

  TARGET_HOST=${SERVERS_LOGDB[${idx}]}

  checkPort $TARGET_HOST 9200 "elasticsearch"
done



for idx in ${!SERVERS_METRICDB[*]}
do

  TARGET_HOST=${SERVERS_METRICDB[${idx}]}

  checkPort $TARGET_HOST 8083 "influxdb"
done



for idx in ${!SERVERS_LB[*]}
do

  TARGET_HOST=${SERVERS_LB[${idx}]}

  checkPort $TARGET_HOST 80 "haproxy"
done


for idx in ${!SERVERS_BATCH[*]}
do

  TARGET_HOST=${SERVERS_BATCH[${idx}]}

  checkPort $TARGET_HOST 9000 "monit-batch"
done
